-- HF-193-A Phase 2.2a: Bridge persistence stored procedure (Path β — RPC atomicity primitive)
--
-- Implements Decision 153 Q-F=F2 signal write site coupling pattern per IRA Consultation 1
-- Option C (bridge returns specs; caller executes atomically) with transaction mechanism
-- per IRA Consultation 2 Path β (RPC via stored procedure).
--
-- Function: fn_bridge_persistence(p_rule_set jsonb, p_signals jsonb) RETURNS uuid
--
-- Atomicity: structural by construction. PostgreSQL functions execute within an implicit
-- server-side transaction. INSERT rule_set + INSERT classification_signals (via unnest) either
-- both succeed or both roll back. No orphans possible.
--
-- Security: SECURITY INVOKER — preserves RLS enforcement through the caller's service-role key.
-- Aligns with T1-E925 Security by Design; avoids SECURITY DEFINER identity shadowing on
-- audit columns (T6-E905 anti-pattern).
--
-- Contract:
--   p_rule_set: jsonb object with fields matching rule_sets table columns, including:
--               id (uuid, pre-generated by caller per T5-E960 + B1 disposition),
--               tenant_id (uuid), name (text), description (text), components (jsonb),
--               input_bindings (jsonb), created_by (uuid), plus any other required fields.
--   p_signals:  jsonb array of signal-write specifications, each element shaped:
--               {metric_name: text, component_index: integer, signal_value: jsonb}
--               tenant_id and signal_type are populated by the function (not by caller).
--               rule_set_id is populated from p_rule_set.id (enforces FK consistency).
--
-- Returns: the uuid of the inserted rule_set (which equals p_rule_set.id — caller pre-generated).
--
-- Callers: bridgeAIToEngineFormat caller sites in
--   web/src/app/api/import/sci/execute/route.ts:1265, :1501
--   (wired up in Phase 2.2b; this migration only defines the function).

BEGIN;

CREATE OR REPLACE FUNCTION fn_bridge_persistence(
  p_rule_set jsonb,
  p_signals  jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_rule_set_id uuid;
  v_tenant_id   uuid;
BEGIN
  -- Extract pre-generated rule_set_id and tenant_id from the JSONB input
  v_rule_set_id := (p_rule_set->>'id')::uuid;
  v_tenant_id   := (p_rule_set->>'tenant_id')::uuid;

  -- Defensive check: both must be present in the input
  IF v_rule_set_id IS NULL THEN
    RAISE EXCEPTION 'fn_bridge_persistence: p_rule_set.id is required (caller must pre-generate UUID)';
  END IF;
  IF v_tenant_id IS NULL THEN
    RAISE EXCEPTION 'fn_bridge_persistence: p_rule_set.tenant_id is required';
  END IF;

  -- INSERT rule_set with full JSONB spread into the rule_sets table.
  -- The caller is responsible for providing a p_rule_set object whose top-level
  -- keys match rule_sets column names. The INSERT uses jsonb_populate_record to
  -- map JSONB fields into typed columns.
  INSERT INTO rule_sets
  SELECT * FROM jsonb_populate_record(NULL::rule_sets, p_rule_set);

  -- INSERT classification_signals for each signal spec in p_signals array.
  -- tenant_id is inherited from the rule_set. signal_type is fixed at 'metric_comprehension'
  -- per Decision 153 / IGF-T2-E01 v2 L2 Comprehension vocabulary.
  -- rule_set_id is inherited from the rule_set being inserted (enforces FK consistency by
  -- construction — no orphan possible because the rule_set and signals are in the same tx).
  INSERT INTO classification_signals (
    tenant_id,
    signal_type,
    signal_value,
    rule_set_id,
    metric_name,
    component_index
  )
  SELECT
    v_tenant_id,
    'metric_comprehension',
    (sig->>'signal_value')::jsonb,
    v_rule_set_id,
    sig->>'metric_name',
    (sig->>'component_index')::integer
  FROM jsonb_array_elements(p_signals) AS sig;

  RETURN v_rule_set_id;
END;
$$;

COMMIT;

-- Post-apply verification query (Phase 2.2a Step 3):
-- SELECT routine_name, security_type, data_type FROM information_schema.routines
--   WHERE routine_name = 'fn_bridge_persistence';
-- SELECT parameter_name, parameter_mode, data_type FROM information_schema.parameters
--   WHERE specific_name LIKE 'fn_bridge_persistence%' ORDER BY ordinal_position;
