/**
 * FRMX Server Commission Plan
 *
 * 3-component compensation plan for restaurant servers.
 * Metrics sourced from POS cheque data via the POS-to-ICM bridge.
 *
 * Components:
 *   1. Revenue Commission  - Tier lookup on server total revenue
 *   2. Tip Performance     - Conditional percentage on tip rate
 *   3. Average Check Bonus - Tier lookup on average check amount
 *
 * Korean Test: All metric names, tier labels, and component names
 * come from the plan configuration data. Zero hardcoded field names.
 */

import type { CompensationPlanConfig } from '@/types/compensation-plan';

// =============================================================================
// PLAN FACTORY
// =============================================================================

export function createFRMXServerPlan(): CompensationPlanConfig {
  return {
    id: 'plan-frmx-server-commission-2025',
    tenantId: 'frmx-demo',
    name: 'FRMX Server Commission Plan',
    description: 'Restaurant server compensation based on POS performance metrics',
    planType: 'additive_lookup',
    status: 'active',
    effectiveDate: '2024-12-01T00:00:00Z',
    endDate: null,
    eligibleRoles: ['server', 'bartender'],
    version: 1,
    previousVersionId: null,
    createdBy: 'system',
    createdAt: new Date().toISOString(),
    updatedBy: 'system',
    updatedAt: new Date().toISOString(),
    approvedBy: 'admin',
    approvedAt: new Date().toISOString(),
    configuration: {
      type: 'additive_lookup',
      variants: [
        {
          variantId: 'server',
          variantName: 'Server',
          description: 'Standard server commission plan',
          eligibilityCriteria: { role: 'server' },
          components: getServerComponents(),
        },
        {
          variantId: 'bartender',
          variantName: 'Bartender',
          description: 'Bartender commission plan with beverage emphasis',
          eligibilityCriteria: { role: 'bartender' },
          components: getBartenderComponents(),
        },
      ],
    },
  };
}

// =============================================================================
// SERVER COMPONENTS
// =============================================================================

function getServerComponents() {
  return [
    // Component 1: Revenue Commission (Tier Lookup)
    {
      id: 'frmx-revenue-commission',
      name: 'Revenue Commission',
      description: 'Monthly payout based on total revenue generated by the server',
      order: 1,
      enabled: true,
      componentType: 'tier_lookup' as const,
      measurementLevel: 'individual' as const,
      tierConfig: {
        metric: 'server_total_revenue',
        metricLabel: 'Total Revenue (MXN)',
        tiers: [
          { min: 0, max: 50000, label: 'Below $50K', value: 0 },
          { min: 50000, max: 75000, label: '$50K - $75K', value: 500 },
          { min: 75000, max: 100000, label: '$75K - $100K', value: 1000 },
          { min: 100000, max: 150000, label: '$100K - $150K', value: 2000 },
          { min: 150000, max: Infinity, label: 'Above $150K', value: 3500 },
        ],
        currency: 'MXN',
      },
    },

    // Component 2: Tip Performance (Conditional Percentage)
    {
      id: 'frmx-tip-performance',
      name: 'Tip Performance',
      description: 'Percentage of tips earned based on achieved tip rate',
      order: 2,
      enabled: true,
      componentType: 'conditional_percentage' as const,
      measurementLevel: 'individual' as const,
      conditionalConfig: {
        conditions: [
          {
            metric: 'server_tip_rate',
            metricLabel: 'Tip Rate',
            min: 0,
            max: 12,
            rate: 0,
            label: 'Below 12% tip rate',
          },
          {
            metric: 'server_tip_rate',
            metricLabel: 'Tip Rate',
            min: 12,
            max: 15,
            rate: 0.02,
            label: '12-15% tip rate',
          },
          {
            metric: 'server_tip_rate',
            metricLabel: 'Tip Rate',
            min: 15,
            max: Infinity,
            rate: 0.03,
            label: 'Above 15% tip rate',
          },
        ],
        appliedTo: 'server_total_tips',
        appliedToLabel: 'Total Tips (MXN)',
      },
    },

    // Component 3: Average Check Bonus (Tier Lookup)
    {
      id: 'frmx-avg-check-bonus',
      name: 'Average Check Bonus',
      description: 'Bonus for maintaining high average check amounts (upselling)',
      order: 3,
      enabled: true,
      componentType: 'tier_lookup' as const,
      measurementLevel: 'individual' as const,
      tierConfig: {
        metric: 'server_avg_check',
        metricLabel: 'Average Check (MXN)',
        tiers: [
          { min: 0, max: 300, label: 'Below $300', value: 0 },
          { min: 300, max: 400, label: '$300 - $400', value: 300 },
          { min: 400, max: 500, label: '$400 - $500', value: 600 },
          { min: 500, max: Infinity, label: 'Above $500', value: 1000 },
        ],
        currency: 'MXN',
      },
    },
  ];
}

// =============================================================================
// BARTENDER COMPONENTS (variant with beverage emphasis)
// =============================================================================

function getBartenderComponents() {
  return [
    // Component 1: Revenue Commission (same structure, slightly different tiers)
    {
      id: 'frmx-bartender-revenue',
      name: 'Revenue Commission',
      description: 'Monthly payout based on total revenue generated',
      order: 1,
      enabled: true,
      componentType: 'tier_lookup' as const,
      measurementLevel: 'individual' as const,
      tierConfig: {
        metric: 'server_total_revenue',
        metricLabel: 'Total Revenue (MXN)',
        tiers: [
          { min: 0, max: 40000, label: 'Below $40K', value: 0 },
          { min: 40000, max: 60000, label: '$40K - $60K', value: 400 },
          { min: 60000, max: 85000, label: '$60K - $85K', value: 900 },
          { min: 85000, max: 120000, label: '$85K - $120K', value: 1800 },
          { min: 120000, max: Infinity, label: 'Above $120K', value: 3000 },
        ],
        currency: 'MXN',
      },
    },

    // Component 2: Tip Performance (same as server)
    {
      id: 'frmx-bartender-tips',
      name: 'Tip Performance',
      description: 'Percentage of tips earned based on tip rate',
      order: 2,
      enabled: true,
      componentType: 'conditional_percentage' as const,
      measurementLevel: 'individual' as const,
      conditionalConfig: {
        conditions: [
          {
            metric: 'server_tip_rate',
            metricLabel: 'Tip Rate',
            min: 0,
            max: 12,
            rate: 0,
            label: 'Below 12% tip rate',
          },
          {
            metric: 'server_tip_rate',
            metricLabel: 'Tip Rate',
            min: 12,
            max: 15,
            rate: 0.02,
            label: '12-15% tip rate',
          },
          {
            metric: 'server_tip_rate',
            metricLabel: 'Tip Rate',
            min: 15,
            max: Infinity,
            rate: 0.03,
            label: 'Above 15% tip rate',
          },
        ],
        appliedTo: 'server_total_tips',
        appliedToLabel: 'Total Tips (MXN)',
      },
    },

    // Component 3: Beverage Mix Bonus (unique to bartender)
    {
      id: 'frmx-bartender-bev-bonus',
      name: 'Beverage Mix Bonus',
      description: 'Bonus for high beverage revenue ratio',
      order: 3,
      enabled: true,
      componentType: 'tier_lookup' as const,
      measurementLevel: 'individual' as const,
      tierConfig: {
        metric: 'server_beverage_ratio',
        metricLabel: 'Beverage Revenue Ratio (%)',
        tiers: [
          { min: 0, max: 30, label: 'Below 30%', value: 0 },
          { min: 30, max: 40, label: '30% - 40%', value: 400 },
          { min: 40, max: 50, label: '40% - 50%', value: 800 },
          { min: 50, max: Infinity, label: 'Above 50%', value: 1200 },
        ],
        currency: 'MXN',
      },
    },
  ];
}

// =============================================================================
// METRICS REQUIRED BY THIS PLAN
// =============================================================================

/**
 * Returns the list of metrics this plan needs from the POS-to-ICM bridge.
 */
export function getRequiredMetrics(): string[] {
  return [
    'server_total_revenue',
    'server_tip_rate',
    'server_total_tips',
    'server_avg_check',
    'server_cheque_count',
    'server_beverage_ratio',
  ];
}
