// HF-193-A Phase 2.2a: RPC verification for fn_bridge_persistence
//
// Exercises the stored procedure established by migration
// 20260421040000_hf_193_a_bridge_persistence_function.sql and asserts structural
// atomicity: one rule_set INSERT + N classification_signals INSERTs must either all
// succeed (returning the pre-generated rule_set_id) or all roll back. Permanent
// regression coverage — re-runnable.
//
// Test payload populates every NOT NULL-with-default column the existing caller at
// execute/route.ts:1285 provides (status, version, population_config, input_bindings,
// components, cadence_config, outcome_config, metadata, created_by) so jsonb_populate_record
// has structural completeness.
//
// Usage:  npx tsx --env-file=.env.local scripts/hf-193-a-phase-2-2a-rpc-verification.ts

import { createClient } from '@supabase/supabase-js';
import { randomUUID } from 'crypto';

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

const MARKER = '__hf_193_a_phase_2_2a_rpc_verification__';

async function main(): Promise<void> {
  console.log('HF-193-A Phase 2.2a verification: fn_bridge_persistence stored procedure');
  console.log('');

  // Discover a valid tenant_id for FK integrity (structural test; no business semantics)
  const { data: tenants, error: tenantErr } = await sb.from('tenants').select('id').limit(1);
  if (tenantErr || !tenants?.[0]) {
    console.error('FAIL: could not read any tenant for structural test', tenantErr);
    process.exit(1);
  }
  const tenantId = tenants[0].id;

  // Discover a valid created_by for FK integrity — reuse an existing rule_set's created_by
  const { data: existingRuleSets, error: rsErr } = await sb
    .from('rule_sets')
    .select('created_by')
    .not('created_by', 'is', null)
    .limit(1);
  if (rsErr || !existingRuleSets?.[0]?.created_by) {
    console.error('FAIL: could not read an existing rule_set.created_by for FK integrity', rsErr);
    process.exit(1);
  }
  const createdBy = existingRuleSets[0].created_by;

  // Caller pre-generates the rule_set UUID (B1 disposition)
  const ruleSetId = randomUUID();

  // jsonb_populate_record does not invoke column DEFAULTs — caller must populate
  // created_at / updated_at explicitly (existing .upsert() caller relies on DEFAULT NOW()
  // because PostgREST omits unsupplied columns from the INSERT).
  const nowIso = new Date().toISOString();

  // Structurally complete test payload — mirrors execute/route.ts:1285 upsert shape
  const testRuleSet = {
    id: ruleSetId,
    tenant_id: tenantId,
    name: MARKER,
    description: 'Phase 2.2a RPC verification row (deleted after verification)',
    status: 'active',
    version: 1,
    population_config: { eligible_roles: [] },
    input_bindings: {},
    components: { variants: [] },
    cadence_config: { period_type: 'monthly' },
    outcome_config: {},
    metadata: { plan_type: 'additive_lookup', source: 'phase_2_2a_verification' },
    created_by: createdBy,
    created_at: nowIso,
    updated_at: nowIso,
  };

  const testSignals = [
    {
      metric_name: `${MARKER}_signal_0`,
      component_index: 0,
      signal_value: { test: true, verification: 'phase_2_2a' },
    },
    {
      metric_name: `${MARKER}_signal_1`,
      component_index: 1,
      signal_value: { test: true, verification: 'phase_2_2a' },
    },
  ];

  console.log('Test rule_set UUID (pre-generated by caller):', ruleSetId);
  console.log('Test tenant_id:', tenantId);
  console.log('Test created_by:', createdBy);
  console.log('Signal count:', testSignals.length);
  console.log('');

  console.log('Invoking fn_bridge_persistence via sb.rpc()...');
  const { data, error } = await sb.rpc('fn_bridge_persistence', {
    p_rule_set: testRuleSet,
    p_signals: testSignals,
  });

  if (error) {
    console.log('RPC INVOCATION FAILED:');
    console.log('  code:', error.code);
    console.log('  message:', error.message);
    console.log('  details:', error.details);
    console.log('  hint:', error.hint);
    console.log('');
    console.log('VERIFICATION: FAIL — fn_bridge_persistence did not execute cleanly.');
    process.exit(1);
  }

  console.log('RPC returned rule_set_id:', data);
  console.log('Round-trip check: returned ID matches pre-generated:', data === ruleSetId);
  console.log('');

  const { data: ruleSetRow } = await sb
    .from('rule_sets')
    .select('id, name, status, version')
    .eq('id', ruleSetId)
    .maybeSingle();
  console.log('rule_sets row:', JSON.stringify(ruleSetRow, null, 2));

  const { data: signalRows } = await sb
    .from('classification_signals')
    .select('id, metric_name, component_index, rule_set_id, signal_type, tenant_id')
    .eq('rule_set_id', ruleSetId)
    .order('component_index', { ascending: true });
  console.log('classification_signals rows count:', signalRows?.length ?? 0);
  console.log('Signal rows:', JSON.stringify(signalRows, null, 2));
  console.log('');

  const asserts: Array<[string, boolean]> = [
    ['RPC returned non-null UUID', data !== null && data !== undefined],
    ['Returned UUID matches pre-generated', data === ruleSetId],
    ['rule_set row persisted', ruleSetRow !== null],
    ['rule_set row name matches input', ruleSetRow?.name === MARKER],
    ['Signal rows count equals input', (signalRows?.length ?? 0) === testSignals.length],
    [
      'Signal rows reference correct rule_set_id',
      (signalRows?.every((s) => s.rule_set_id === ruleSetId) ?? false),
    ],
    [
      'Signal signal_type is metric_comprehension',
      (signalRows?.every((s) => s.signal_type === 'metric_comprehension') ?? false),
    ],
    [
      'Signal tenant_id populated from rule_set',
      (signalRows?.every((s) => s.tenant_id === tenantId) ?? false),
    ],
    [
      'Signal metric_name matches input',
      (signalRows?.map((s) => s.metric_name).sort().join(',') ===
        testSignals.map((s) => s.metric_name).sort().join(',')),
    ],
    [
      'Signal component_index populated (not null)',
      (signalRows?.every((s) => s.component_index !== null) ?? false),
    ],
  ];

  console.log('Structural assertions:');
  let allPass = true;
  for (const [label, pass] of asserts) {
    console.log(`  ${pass ? 'PASS' : 'FAIL'}  ${label}`);
    if (!pass) allPass = false;
  }
  console.log('');

  // Cleanup — children first (FK), then parent
  await sb.from('classification_signals').delete().eq('rule_set_id', ruleSetId);
  await sb.from('rule_sets').delete().eq('id', ruleSetId);
  console.log('Cleanup complete (test rows deleted).');
  console.log('');

  if (allPass) {
    console.log('VERIFICATION: PASS — fn_bridge_persistence executes atomically; signals persist correctly.');
    process.exit(0);
  } else {
    console.log('VERIFICATION: FAIL — one or more structural assertions failed. Investigate before Phase 2.2b.');
    process.exit(1);
  }
}

main().catch((err) => {
  console.error('Verification script error:', err);
  process.exit(1);
});
