'use client';

/**
 * OB-257 O4 — Revenue insight slot (entitlement-aware).
 *
 * The Intelligence entitlement (intelligence_enabled) decides what this slot IS:
 *  - not entitled -> a quiet upsell placeholder (the PLG hook) — NO fetch, NO computation;
 *  - entitled     -> one fetch of /api/revenue/insights on mount, up to 6 insights rendered.
 *
 * THEME (Rule 30): shadcn semantic classes only (bg-card via Card, text-foreground,
 * text-muted-foreground, border-border) — zero color literals. i18n: bilingual via
 * isSpanishLocale(locale); insight kind labels are localized here (the route serves machine keys).
 */

import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { useFeature, useTenant } from '@/contexts/tenant-context';
import { useLocale, isSpanishLocale } from '@/contexts/locale-context';
import type { RevenueInsightKind } from '@/lib/revenue/types';

interface ServedInsight {
  id: string;
  kind: RevenueInsightKind | null;
  title: string;
  narrative: string | null;
  severity: string | null;
  entityId: string | null;
  entityName: string | null;
  dataReferences: unknown[];
  createdAt: string;
  periodStart: string | null;
  periodEnd: string | null;
}

// bilingual labels for the four structural insight kinds (machine keys come from the route)
const KIND_LABELS: Record<RevenueInsightKind, { en: string; es: string }> = {
  momentum_shift: { en: 'Momentum', es: 'Impulso' },
  mix_shift: { en: 'Mix Shift', es: 'Cambio de Composición' },
  concentration_alert: { en: 'Concentration', es: 'Concentración' },
  incentive_yield_outlier: { en: 'Incentive Yield', es: 'Rendimiento de Incentivos' },
};

interface InsightSlotProps {
  className?: string;
}

export function InsightSlot({ className }: InsightSlotProps) {
  const intelligenceEnabled = useFeature('intelligence_enabled');
  // HF-374: switcher-effective tenant — the insights route REQUIRES ?tenantId= (resolveCallerTenant validates).
  const { currentTenant } = useTenant();
  const tenantId = currentTenant?.id;
  const { locale } = useLocale();
  const isSpanish = isSpanishLocale(locale);

  const [insights, setInsights] = useState<ServedInsight[] | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    if (!intelligenceEnabled) return; // upsell placeholder — no fetch, no computation
    if (!tenantId) return; // quiet loading state holds; effect re-fires when the tenant context resolves (HF-374)
    let cancelled = false;
    fetch(`/api/revenue/insights?tenantId=${encodeURIComponent(tenantId)}`)
      .then((res) => (res.ok ? res.json() : Promise.reject(new Error(String(res.status)))))
      .then((body) => {
        if (!cancelled) setInsights(Array.isArray(body?.insights) ? body.insights : []);
      })
      .catch(() => {
        if (!cancelled) setFailed(true);
      });
    return () => {
      cancelled = true;
    };
  }, [intelligenceEnabled, tenantId]);

  const title = isSpanish ? 'Insights de Ingresos' : 'Revenue Insights';

  // ── Not entitled: the PLG hook — a quiet, truthful placeholder ────────────────
  if (!intelligenceEnabled) {
    return (
      <Card className={className}>
        <CardHeader>
          <CardTitle className="text-sm font-medium text-muted-foreground">{title}</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground">
            {isSpanish
              ? 'Los insights de ingresos los genera el agente de Inteligencia. Contacta a tu administrador para activarlo.'
              : 'Revenue insights are generated by the Intelligence agent. Contact your administrator to enable it.'}
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle className="text-sm font-medium">{title}</CardTitle>
      </CardHeader>
      <CardContent>
        {failed ? (
          <p className="text-sm text-muted-foreground">
            {isSpanish ? 'No se pudieron cargar los insights.' : 'Insights could not be loaded.'}
          </p>
        ) : insights === null ? (
          <p className="text-sm text-muted-foreground animate-pulse">
            {isSpanish ? 'Cargando insights...' : 'Loading insights...'}
          </p>
        ) : insights.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            {isSpanish
              ? 'Aún no hay insights de ingresos — se generan cuando se importan datos o se activa el agente.'
              : 'No revenue insights yet — they generate when data is imported or the agent is activated.'}
          </p>
        ) : (
          <ul className="space-y-4">
            {insights.slice(0, 6).map((insight) => {
              const label = insight.kind ? KIND_LABELS[insight.kind] : null;
              return (
                <li key={insight.id} className="border-b border-border pb-3 last:border-b-0 last:pb-0">
                  <div className="flex items-start gap-2">
                    {label && (
                      <Badge variant="outline" className="shrink-0">
                        {isSpanish ? label.es : label.en}
                      </Badge>
                    )}
                    <span className="text-sm font-medium text-foreground">{insight.title}</span>
                  </div>
                  {insight.narrative && (
                    <p className="mt-1 text-sm text-muted-foreground">{insight.narrative}</p>
                  )}
                  {insight.severity && (
                    <p className="mt-1 text-xs text-muted-foreground">{insight.severity}</p>
                  )}
                </li>
              );
            })}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}
