-- OB-204 Phase B — User Contract Enforcement (CC authors; ARCHITECT applies via Dashboard SQL Editor, SR-44).
-- Re-runnable (guards on every DDL). Order is load-bearing: normalize data BEFORE adding CHECK constraints.
-- Capability arrays below are deriveCapabilities() output VERBATIM (single source; generated by
-- scripts/ob204-phaseb-gen.ts). Pre-flight (same script) confirmed CONSTRAINT-SAFE: 11 profiles,
-- 0 duplicate auth_user_id, 0 role/tenant incoherence. ALL 11 rows are normalized to the matrix
-- (architect disposition): every stored array matches deriveCapabilities(role) verbatim, not just
-- the 3 object-shaped rows — closes the SOC 2 CC6 stored-vs-computed discrepancy for 11/11.

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- (1) NORMALIZATION — renames first (so capability derivation keys on the canonical role),
--     then EVERY row's capabilities → role-derived array (DS-028 §2: derived-at-write; lossless,
--     authz is role-based). Widened from object-only to all rows per architect disposition.
-- ─────────────────────────────────────────────────────────────────────────────
UPDATE public.profiles SET role = 'admin'  WHERE role = 'tenant_admin';   -- guarded literal
UPDATE public.profiles SET role = 'member' WHERE role = 'sales_rep';      -- guarded literal

UPDATE public.profiles SET capabilities = '["data.advance_lifecycle","data.approve_results","data.calculate","data.export","data.import","data.reconcile","data.upload_storage","dispute.resolve","dispute.submit","icm.configure_plans","icm.simulate","icm.view_plan_details","platform.access_observatory","platform.provision_tenant","platform.system_config","platform.view_all_tenants","statement.view","tenant.configure_entities","tenant.configure_periods","tenant.edit_settings","tenant.manage_users","tenant.view_settings","view.all_entities","view.all_results","view.audit_trail","view.intelligence_stream","view.own_results","view.team_entities","view.team_results"]'::jsonb
  WHERE role ='platform';
UPDATE public.profiles SET capabilities = '["data.advance_lifecycle","data.approve_results","data.calculate","data.export","data.import","data.reconcile","data.upload_storage","dispute.resolve","dispute.submit","icm.configure_plans","icm.simulate","icm.view_plan_details","statement.view","tenant.configure_entities","tenant.configure_periods","tenant.edit_settings","tenant.manage_users","tenant.view_settings","view.all_entities","view.all_results","view.audit_trail","view.intelligence_stream","view.own_results","view.team_entities","view.team_results"]'::jsonb
  WHERE role ='admin';
UPDATE public.profiles SET capabilities = '["data.approve_results","dispute.resolve","dispute.submit","icm.view_plan_details","statement.view","tenant.view_settings","view.intelligence_stream","view.own_results","view.team_entities","view.team_results"]'::jsonb
  WHERE role ='manager';
UPDATE public.profiles SET capabilities = '["dispute.submit","statement.view","view.intelligence_stream","view.own_results"]'::jsonb
  WHERE role ='member';
UPDATE public.profiles SET capabilities = '["statement.view","view.intelligence_stream","view.own_results"]'::jsonb
  WHERE role ='viewer';

-- ─────────────────────────────────────────────────────────────────────────────
-- (2) STATUS COLUMN (Q-D) — disable/enable state; default active.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_status_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_status_check CHECK (status IN ('active','disabled'));

-- ─────────────────────────────────────────────────────────────────────────────
-- (3) CONTRACT CONSTRAINTS (DS-028 §2) — the contract becomes a DB invariant.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_auth_user_id_unique;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_auth_user_id_unique UNIQUE (auth_user_id);  -- HF-282 deferral, now installed

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_canon;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_canon CHECK (role IN ('platform','admin','manager','member','viewer'));

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_capabilities_array;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_capabilities_array CHECK (jsonb_typeof(capabilities) = 'array');

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_platform_tenant;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_platform_tenant CHECK ((role = 'platform') = (tenant_id IS NULL));

-- ─────────────────────────────────────────────────────────────────────────────
-- (4) FK SAFETY NET — profiles.auth_user_id ON DELETE SET NULL, so a true auth-row deletion
--     RETAINS the profile tombstone (GDPR Art 17) instead of cascade-deleting it. (Phase-A finding.)
--     Introspects the existing FK name so this is robust to whatever it is named.
-- ─────────────────────────────────────────────────────────────────────────────
DO $$
DECLARE fk_name text;
BEGIN
  ALTER TABLE public.profiles ALTER COLUMN auth_user_id DROP NOT NULL;  -- SET NULL target must be nullable
  SELECT con.conname INTO fk_name
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = ANY (con.conkey)
    WHERE nsp.nspname = 'public' AND rel.relname = 'profiles' AND con.contype = 'f' AND att.attname = 'auth_user_id'
    LIMIT 1;
  IF fk_name IS NOT NULL THEN EXECUTE format('ALTER TABLE public.profiles DROP CONSTRAINT %I', fk_name); END IF;
  ALTER TABLE public.profiles
    ADD CONSTRAINT profiles_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- (5) AUDIT_LOGS NULLABLE TENANT — platform-target lifecycle audit rows carry NULL tenant
--     (platform users have no tenant). (Phase-A finding: writes failed on NOT NULL.)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.audit_logs ALTER COLUMN tenant_id DROP NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- (6) RETROACTIVE PII CLEANSE (Q-I corrected, F-3) — strip email/ip/user_agent from platform_events
--     payloads older than the 90-day retention window. I-1 prevents NEW PII, so this decays to a no-op.
-- ─────────────────────────────────────────────────────────────────────────────
UPDATE public.platform_events
  SET payload = payload - 'email' - 'ip_address' - 'ip' - 'user_agent'
  WHERE created_at < now() - interval '90 days'
    AND (payload ? 'email' OR payload ? 'ip_address' OR payload ? 'ip' OR payload ? 'user_agent');

COMMIT;
